export const BranchData = {
  BT: {
    additionalRollNumbers: ["19BT8022", "19BT8037", "19BT8045"],
    start: 8001,
    end: 8068,
    name: "Biotechnology",
    code: "BT",
  },
  CE: {
    additionalRollNumbers: [],
    start: 8001,
    end: 8079,
    name: "Civil Engineering",
    code: "CE",
  },
  CH: {
    additionalRollNumbers: [],
    start: 8001,
    end: 8076,
    name: "Chemical Engineering",
    code: "CH",
  },
  CS: {
    additionalRollNumbers: [
      "19CS8006",
      "19CS8034",
      "18CS8038",
      "18CS8043",
      "18CS8095",
    ],
    start: 8001,
    end: 8201,
    name: "Computer Science and Engineering",
    code: "CS",
  },
  EC: {
    additionalRollNumbers: [],
    start: 8001,
    end: 8098,
    name: "Electronics and Communication Engineering",
    code: "EC",
  },
  ME: {
    additionalRollNumbers: ["18ME8151", "18ME8155"],
    start: 8001,
    end: 8191,
    name: "Mechanical Engineering",
    code: "ME",
  },
  EE: {
    additionalRollNumbers: ["19ME8158"],
    start: 8001,
    end: 8103,
    name: "Electrical Engineering",
    code: "EE",
  },
  MM: {
    additionalRollNumbers: [],
    start: 8001,
    end: 8067,
    name: "Metallurgical and Materials Engineering",
    code: "MM",
  },
  "DD-BT": {
    additionalRollNumbers: [],
    start: null,
    end: null,
    name: "Biotechnology-Dual Degree",
    code: "BT",
  },
  "DD-CH": {
    additionalRollNumbers: [],
    start: 1001,
    end: 1005,
    name: "Chemical Engineering-Dual Degree",
    code: "CH",
  },
  CY: {
    additionalRollNumbers: [],
    start: 1001,
    end: 1015,
    name: "Integrated M.Sc. in Chemistry",
    code: "CY",
  },
};
